### ISSUE TITLE
Regex for input

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/merge-markdown#29]
As a user, I want to be able to add regex values to the `input` param so that I don't have to manually write out every single file in the manifest. Examples:

#### Any file in the current directory starting with `module-`
```yaml
input:
  frontmatter: ""
  module-*:  {noYAML: true}
```
#### Any file in the current directory starting with a number
```yaml
input:
  frontmatter: ""
  ^[0-9]:  {noYAML: true}
```
#### Any file in the current directory ending with a `word`
```yaml
input:
  frontmatter: ""
  word$:  {noYAML: true}
```
#### Any file in `module/` ending in `-chapter.md`
```yaml
input:
  /(?<=module/).*(?=-chapter.md)/g: ""
  module-*: {noYAML: true}
```
