### ISSUE TITLE
Add simple example in README

### ISSUE THREAD

**Issue by sanjarcode** [knennigtri/merge-markdown#57]
I have the following folder:
![image](https://github.com/knennigtri/merge-markdown/assets/48156230/b76e4884-25b9-4fe0-905f-4b0c66b6d597)

How to generate a single md ? I couldn't figure it out using the README. 
Maybe add the trivial case first, before discussion variations in README

**Comment by knennigtri** [comment]
The main thing is you need to create a manifest file. You can see an example of one directly in the tool using help:
```
 merge-markdown -h manifest
```

For your usecase, it would be something like:

./manifest.yml
```
---
  input:
    home/1_motivation.md: ""
    home/2_resources.md: {noYAML: true}
    home/3_roadmap.md: {noYAML: true}
    home/4_resouce_itineraries: {noYAML: true}
    home/5_project.md: {noYAML: true}
    home/6_setup.md: {noYAML: true}
  output: 
    name: merged/myOutputFile.md
---
```

Then you can simply run the command:
```
    $ merge-markdown -m manifest.yml
```

Good luck!
