### ISSUE TITLE
merging nested md files

### ISSUE THREAD

**Issue by bumberboy** [knennigtri/merge-markdown#58]
Hello there! Thanks for creating this. May I know how can I merge all md files in a directory including those in sub-directories?

**Comment by knennigtri** [comment]
You manifest would look something the below... because the manifest controls which files are included (and what order), you have to explicitly write each file out:

```
---
input:
 frontmatter.md: {...}
 subfolder1/m1-example.md: {...}
 subfolder2/m2-example.md: {...}
 anotherFolder/myfolder/anotherExample.md: {...}
 C:/this/is/an/absolute/path/myFile.md: {...}
output: 
 name: merged/myOutput.md
```
