### ISSUE TITLE
Add module numbers

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/merge-markdown#8]
Potentially inject **Module #** into the header #

**Comment by knennigtri** [comment]
This can currently be solved by using a file specific replace:

myFile.md
```markdown
# <!--#-->My Awesome Title
In this chapter we will discuss the history of space flight
```

my-manifest.md
```yaml
input:
   myFile.md: {noYAML: true, TOC: true, replace: {<!--#-->: "Module 1: "}}
   myFile2.md: {noYAML: true, TOC: true, replace: {<!--#-->: "Module 2: "}}
   myFile3.md: {noYAML: true, TOC: true, replace: {<!--#-->: "Module 3: "}}
```

output:
```markdown
# Module1: My Awesome Title
In this chapter we will discuss the history of space flight
```
